import * as esbuild from 'esbuild';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'fs';
import { join, basename, extname } from 'path';

const outDir = 'dist';
if (!existsSync(outDir)) {
    mkdirSync(outDir);
}

/**
 * Scans directories and generates a manifest file for index.js to import.
 * This avoids having to manually add every new file to index.js.
 */
function generateManifest() {
    const folders = {
        extensions: 'src/extensions',
        components: 'src/components',
        services: 'src/services'
    };

    let imports = '';
    let registration = '\n// Automatic registration\n';

    Object.entries(folders).forEach(([type, path]) => {
        if (!existsSync(path)) return;

        const files = readdirSync(path).filter(f => f.endsWith('.js') && !f.startsWith('_'));

        files.forEach((file, index) => {
            let name = basename(file, extname(file));

            // Handle naming exceptions and conventions
            if (file === 'wire-client.js') name = 'wire';
            else if (file === 'wire-service.js') name = 'wireservice';
            else if (name.includes('-')) {
                // camelCase: dom-css -> domCss
                name = name.split('-').map((part, i) => i === 0 ? part : part[0].toUpperCase() + part.slice(1)).join('');
            }

            const varName = `${type}_${index}`;
            const importPath = `./${type}/${file}`;

            imports += `import ${varName} from '${importPath}';\n`;

            if (type === 'services') {
                let svcName = name.charAt(0).toUpperCase() + name.slice(1) + 'Service';
                registration += `VanillaBrick.services['${svcName}'] = ${varName};\n`;
            } else {
                registration += `if (${varName}) {\n`;
                registration += `  VanillaBrick.extensions['${name}'] = ${varName};\n`;
                registration += `}\n`;
            }
        });
    });

    const content = `/**
 * AUTO-GENERATED MANIFEST
 * Do not edit manually. This file is generated by scripts/build.mjs
 */
${imports}
export function registerBuiltins(VanillaBrick) {
${registration}
}
`;

    writeFileSync('src/_manifest.js', content);
    console.log('Manifest generated: src/_manifest.js');
}

async function build() {
    generateManifest();

    const common = {
        entryPoints: ['src/index.js'],
        bundle: true,
        sourcemap: true,
        target: ['es2017'],
        platform: 'browser',
    };

    try {
        // 1. Browser IIFE - Minified
        await esbuild.build({
            ...common,
            minify: true,
            format: 'iife',
            outfile: join(outDir, 'vanillabrick.min.js'),
        });
        console.log(`Build complete: ${join(outDir, 'vanillabrick.min.js')}`);

        // 2. Browser IIFE - Unminified
        await esbuild.build({
            ...common,
            minify: false,
            format: 'iife',
            outfile: join(outDir, 'vanillabrick.js'),
        });
        console.log(`Build complete: ${join(outDir, 'vanillabrick.js')}`);

        // 3. Bundled ESM build
        await esbuild.build({
            ...common,
            minify: false,
            format: 'esm',
            outfile: join(outDir, 'vanillabrick.esm.js'),
        });
        console.log(`Build complete: ${join(outDir, 'vanillabrick.esm.js')}`);

    } catch (e) {
        console.error('Build failed', e);
        process.exit(1);
    }
}

build();
