/**
 * AUTO-GENERATED MANIFEST
 * Do not edit manually. This file is generated by scripts/build.mjs
 */
import extensions_0 from './extensions/dom-css.js';
import extensions_1 from './extensions/dom-events.js';
import extensions_2 from './extensions/dom.js';
import extensions_3 from './extensions/store.js';
import extensions_4 from './extensions/wire-client.js';
import extensions_5 from './extensions/wire-service.js';
import components_0 from './components/form-items.js';
import components_1 from './components/form-record.js';
import components_2 from './components/form.js';
import components_3 from './components/grid-columns.js';
import components_4 from './components/grid-rows-focused.js';
import components_5 from './components/grid-rows.js';
import components_6 from './components/grid.js';
import services_0 from './services/wire.js';

export function registerBuiltins(VanillaBrick) {

// Automatic registration
if (extensions_0) {
  VanillaBrick.extensions['domCss'] = extensions_0;
}
if (extensions_1) {
  VanillaBrick.extensions['domEvents'] = extensions_1;
}
if (extensions_2) {
  VanillaBrick.extensions['dom'] = extensions_2;
}
if (extensions_3) {
  VanillaBrick.extensions['store'] = extensions_3;
}
if (extensions_4) {
  VanillaBrick.extensions['wire'] = extensions_4;
}
if (extensions_5) {
  VanillaBrick.extensions['wireservice'] = extensions_5;
}
if (components_0) {
  VanillaBrick.extensions['formItems'] = components_0;
}
if (components_1) {
  VanillaBrick.extensions['formRecord'] = components_1;
}
if (components_2) {
  VanillaBrick.extensions['form'] = components_2;
}
if (components_3) {
  VanillaBrick.extensions['gridColumns'] = components_3;
}
if (components_4) {
  VanillaBrick.extensions['gridRowsFocused'] = components_4;
}
if (components_5) {
  VanillaBrick.extensions['gridRows'] = components_5;
}
if (components_6) {
  VanillaBrick.extensions['grid'] = components_6;
}
VanillaBrick.services['WireService'] = services_0;

}
